name: ipa-chatbot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip=24.0
  - nodejs=20.10
  - npm=10.2
  - pip:
    - fastapi==0.104.0
    - uvicorn==0.23.2
    - pydantic==2.4.2
    - pydantic-settings==2.0.3
    - jinja2==3.1.2
    - chromadb==0.4.18
    - sentence-transformers==2.2.2
    - pandas==2.1.1
    - python-dotenv==1.0.0
    - requests==2.31.0
  # Frontend-NPM-Pakete (werden über npm installiert)
  # Diese sind hier nur zur Referenz aufgeführt. Nach dem Aktivieren der Conda-Umgebung
  # musst du im Frontend-Verzeichnis trotzdem 'npm install' ausführen.
  - npm:
    - react@19.1.0
    - react-dom@19.1.0
    - react-router-dom@7.6.0
    - react-markdown@10.1.0
    - axios@1.9.0
    - bootstrap@5.3.6
    - github-markdown-css@5.8.1
    - react-syntax-highlighter@15.6.1
    - remark-gfm@4.0.1
